# Generated by Django 4.0.6 on 2022-07-27 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='active',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='created_at',
        ),
    ]
