# Generated by Django 4.0.6 on 2022-07-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_remove_owner_active_remove_owner_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='health_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='vaccines',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='owner',
            name='is_adult',
            field=models.BooleanField(default=False),
        ),
    ]
