# Generated by Django 4.0.6 on 2022-08-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_health_certificate_pet_vaccines_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='health_certificate',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='vaccines',
        ),
        migrations.AlterField(
            model_name='owner',
            name='any_allergies',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='owner',
            name='family_agrees',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='owner',
            name='had_pets_in_the_past',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='owner',
            name='have_children',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='owner',
            name='have_pets_now',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='owner',
            name='is_adult',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='place_to_keep',
            field=models.CharField(choices=[('house', 'House'), ('garden', 'Garden'), ('crate', 'Crate'), ('other', 'Other')], default='house', max_length=6),
        ),
        migrations.AlterField(
            model_name='owner',
            name='reasons_for_adoption',
            field=models.TextField(default=''),
        ),
    ]
