# Generated by Django 4.0.6 on 2022-08-01 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_remove_pet_health_certificate_remove_pet_vaccines_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='adopted',
        ),
        migrations.AddField(
            model_name='owner',
            name='file',
            field=models.FileField(null=True, upload_to='static/image/owner_profile'),
        ),
        migrations.AddField(
            model_name='pet',
            name='file',
            field=models.FileField(null=True, upload_to='static/image/pets'),
        ),
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('new_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
        ),
    ]
