# Generated by Django 4.0.6 on 2022-08-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_species_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog'), ('rabbit', 'Rabbit'), ('hamster', 'Hamster'), ('bird', 'Birds')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Species',
        ),
    ]
