# Generated by Django 4.0.6 on 2022-08-02 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_species_alter_pet_species'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Species',
            new_name='Specie',
        ),
    ]
