# Generated by Django 4.0.3 on 2022-08-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_rename_species_specie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='any_allergies',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='family_agrees',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='had_pets_in_the_past',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='have_children',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='have_pets_now',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='place_to_keep',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='reasons_for_adoption',
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='any_allergies',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='family_agrees',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='had_pets_in_the_past',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='have_children',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='have_pets_now',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='place_to_keep',
            field=models.CharField(choices=[('house', 'House'), ('garden', 'Garden'), ('crate', 'Crate'), ('other', 'Other')], default='house', max_length=6),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='reasons_for_adoption',
            field=models.TextField(default=''),
        ),
    ]
