# Generated by Django 4.0.6 on 2022-08-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0011_remove_owner_any_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specie',
            name='navbar_promo',
            field=models.BooleanField(default=False),
        ),
    ]
