# Generated by Django 4.0.3 on 2022-08-09 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0013_specie_name_plural'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='users_favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite_pet', to=settings.AUTH_USER_MODEL),
        ),
    ]
