# Generated by Django 4.0.3 on 2022-08-09 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0014_pet_users_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='users_favourite',
            field=models.ManyToManyField(blank=True, related_name='users_favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
