# Generated by Django 4.0.6 on 2022-08-10 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0018_blogpost_created_at_blogpost_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryblog',
            old_name='specie_name',
            new_name='specie',
        ),
    ]
