# Generated by Django 4.0.6 on 2022-08-10 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0019_rename_specie_name_categoryblog_specie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='specie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.specie'),
        ),
        migrations.DeleteModel(
            name='CategoryBlog',
        ),
    ]
