# Generated by Django 4.0.3 on 2022-08-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0020_remove_blogpost_category_blogpost_specie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='file',
            field=models.ImageField(null=True, upload_to='static/image/blog'),
        ),
    ]
