# Generated by Django 4.0.6 on 2022-08-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0021_blogpost_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='confirmed',
            field=models.BooleanField(default=None),
        ),
    ]
