# Generated by Django 4.0.3 on 2022-08-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0024_alter_adoptionrequest_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='file',
            field=models.ImageField(null=True, upload_to='static/image/owner_profile'),
        ),
    ]
