# Generated by Django 4.0.6 on 2022-08-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0027_alter_pet_age_alter_pet_breed_alter_pet_coat_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed_size',
            field=models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=6, null=True),
        ),
    ]
